### ISSUE TITLE
Add counter effect to the "Numbers Speak Louder" Section

### ISSUE THREAD

**Issue by coderbysoul** [Codess-Cafe/Codess-Website#64]
The section currently looks like this-->
![image](https://github.com/Codess-Cafe/Codess-Website/assets/96008596/4b18cdf5-ca27-4430-8ed2-e451e2767e3c)

I want to add a counter which counts up to the desired stats when a user sees the numbers(on page load).
I have worked on this in my local in order to give a demo. Here is it:--

https://github.com/Codess-Cafe/Codess-Website/assets/96008596/51f6c38d-155f-4399-824c-1b6640ddad7d

Can I work on this issue?

**Comment by VidhiBhatt01** [comment]
make this animation slightly slower

**Comment by coderbysoul** [comment]
> make this animation slightly slower

https://github.com/Codess-Cafe/Codess-Website/assets/96008596/02d17cf5-9ad4-4ed2-aa1a-3d740a0063a2

Is this ok? Or should I make it slower

**Comment by VidhiBhatt01** [comment]
perfect

**Comment by VidhiBhatt01** [comment]
do git pull before raising PR

**Comment by coderbysoul** [comment]
> do git pull before raising PR

Sure

**Comment by coderbysoul** [comment]
> do git pull before raising PR

After doing git pull, I notices that the changes that I had made in 62 are not there in the code, I also checked the code in github now and found out that it is not there.
The animation on scroll feature which I did today is currently not there after the latest pr it seems, what should I do now

**Comment by VidhiBhatt01** [comment]
Seems like someone messed it up in their PR. Not sure how it went unnoticed by me during code review. Please add it again in the same PR. You can get your code from the merged PR

**Comment by VidhiBhatt01** [comment]
https://github.com/Codess-Cafe/Codess-Website/commit/8562a504a301ecbb297b5a586e542d7cc747f3dc

identified the cause

**Comment by coderbysoul** [comment]
> Seems like someone messed it up in their PR. Not sure how it went unnoticed by me during code review. Please add it again in the same PR. You can get your code from the merged PR

Should I add that missing code in the new pr which I will make for this issue? Or the old pr

**Comment by VidhiBhatt01** [comment]
I fixed it, please pull again

**Comment by coderbysoul** [comment]
> I fixed it, please pull again

I pulled, but saw that the animation is still not there, I checked that some other codes are also missing from that pr. Should I add them in this pr?

**Comment by coderbysoul** [comment]
![image](https://github.com/Codess-Cafe/Codess-Website/assets/96008596/65a37a64-f84d-4802-bbf6-424fa87ac3c7)
![image](https://github.com/Codess-Cafe/Codess-Website/assets/96008596/81cc7274-dbd2-4b3c-a164-671f6f540217)
These two were removed in https://github.com/Codess-Cafe/Codess-Website/commit/8562a504a301ecbb297b5a586e542d7cc747f3dc

**Comment by VidhiBhatt01** [comment]
Yes please add them

**Comment by coderbysoul** [comment]
> Yes please add them
Done
